"""The ONLY module in this repo allowed to write .mdp text.

Every key emitted must be declared in ontology.json, so a knob that isn't in the
agent's comprehension surface cannot secretly exist in a simulation.
"""

from __future__ import annotations

from . import ontology

# hand-verified against the GROMACS 2026 mdp reference.
# logical key (as used in a Plan / ontology) -> literal mdp key
ALIASES = {
    "epsilon_r": "epsilon-r",
    "epsilon_rf": "epsilon-rf",
}

# emission order: grouped the way a human reads an mdp file
EMIT_ORDER = [
    # run control
    "integrator", "dt", "nsteps", "tinit", "init-step",
    "emtol", "emstep",
    "comm-mode", "nstcomm",
    # output
    "nstxout-compressed", "compressed-x-precision", "nstenergy", "nstlog",
    "nstxout", "nstvout", "nstfout",
    # neighbour search
    "cutoff-scheme", "nstlist", "pbc", "verlet-buffer-tolerance", "rlist",
    # electrostatics / vdw
    "coulombtype", "rcoulomb", "coulomb-modifier", "epsilon_r", "epsilon_rf",
    "fourierspacing", "pme-order", "ewald-rtol",
    "vdwtype", "vdw-modifier", "rvdw", "rvdw-switch", "DispCorr",
    # constraints
    "constraints", "constraint-algorithm", "lincs-order", "lincs-iter",
    "mass-repartition-factor",
    # temperature coupling
    "tcoupl", "tc-grps", "tau-t", "ref-t", "nsttcouple",
    # pressure coupling
    "pcoupl", "pcoupltype", "tau-p", "ref-p", "compressibility",
    "nstpcouple", "refcoord-scaling",
    # velocity generation / continuation
    "gen-vel", "gen-temp", "gen-seed", "continuation", "ld-seed",
    # restraints
    "define",
]


class MdpError(ValueError):
    pass


def _fmt(v):
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, (list, tuple)):
        return " ".join(_fmt(x) for x in v)
    if isinstance(v, float):
        return f"{v:g}"
    return str(v)


def emit_mdp(resolved_stage: dict) -> str:
    """resolved stage {'name', 'type', 'mdp': {key: value}} -> .mdp text."""
    mdp = resolved_stage["mdp"]

    # every emitted key must exist in the ontology (under either spelling)
    for k in mdp:
        if not (ontology.known(k) or ontology.known(k.replace("-", "_"))):
            raise MdpError(
                f"'{k}' is not declared in ontology.json — mdp_emit refuses to write "
                f"an undocumented knob. Add it to the ontology first.")

    lines = [f"; {resolved_stage['name']}  ({resolved_stage['type']})",
             "; generated by labkit.plan.mdp_emit — do not hand-edit", ""]
    written = set()
    width = max((len(ALIASES.get(k, k)) for k in mdp), default=10)
    for key in EMIT_ORDER:
        if key in mdp:
            lines.append(f"{ALIASES.get(key, key):<{width}} = {_fmt(mdp[key])}")
            written.add(key)
    leftover = [k for k in mdp if k not in written]
    if leftover:
        lines.append("")
        lines.append("; --- additional keys ---")
        for k in sorted(leftover):
            lines.append(f"{ALIASES.get(k, k):<{width}} = {_fmt(mdp[k])}")
    return "\n".join(lines) + "\n"
